# TODO
- check missing dates

In [1]:
%matplotlib notebook
import pandas as pd, numpy as np
import matplotlib.pyplot as plt
import sys

sys.path.append('../')
pd.options.display.max_columns = 35

In [2]:
data_path = '../data/raw/'

In [3]:
train = pd.read_csv(data_path + "train_1.csv", header=0, delimiter=";",decimal=',',
                    parse_dates=['date'], index_col='date')

In [4]:
train.head(5)

,insee,tH2_obs,capeinsSOL0,ciwcH20,clwcH20,ddH10_rose4,ffH10,flir1SOL0,fllat1SOL0,flsen1SOL0,flvis1SOL0,hcoulimSOL0,huH2,iwcSOL0,nbSOL0_HMoy,nH20,ntSOL0_HMoy,pMER0,rr1SOL0,rrH20,tH2,tH2_VGrad_2.100,tH2_XGrad,tH2_YGrad,tpwHPA850,ux1H10,vapcSOL0,vx1H10,ech,mois
date,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
2014-01-01,6088001,5.5,0.198757,0.0,0.000000,4.0,1.970260,-386960.595711,-94260.682523,-40545.510054,3.600000e-12,66.600368,79.211738,0.0,0.000000,0.00000,4.173220,1019.543734,0.000000,0.000000,9.034338,-0.084999,0.007725,-0.013024,3.852825,1.330320,10.664653,-2.853134,1,janvier
2014-01-01,31069001,4.8,8.590036,0.0,0.000000,3.0,2.755962,-200181.123871,2282.951687,14399.918192,3.600000e-12,57.954614,83.862960,0.0,0.012709,0.00000,5.736559,1018.290035,0.000000,0.000000,3.853128,1.396138,0.005036,0.000810,8.476699,-2.040020,15.462043,3.019614,1,janvier
2014-01-01,33281001,8.9,69.203856,0.0,0.000001,3.0,3.411283,-62310.340297,9483.691316,64790.365136,3.600000e-12,202.985582,95.711708,0.0,4.792424,0.15494,7.844538,1016.139756,0.081315,0.005008,8.585184,0.387329,0.001372,0.000010,7.643070,3.029610,17.343600,4.889849,1,janvier
2014-01-01,35281001,6.8,65.270316,0.0,0.000000,3.0,4.655633,-61612.120075,-48356.475831,127450.659115,3.600000e-12,343.974193,90.178385,0.0,7.074669,0.00000,7.377704,1009.321502,0.029946,0.008139,7.304130,-0.089267,0.000401,-0.000067,7.089030,-1.027446,13.981847,8.079973,1,janvier
2014-01-01,59343001,5.4,5.932505,0.0,0.000000,3.0,5.855930,-39553.109955,-1022.914242,117800.171480,3.600000e-12,656.972741,92.680476,0.0,7.995791,0.00000,7.995791,1008.724301,0.000000,0.000000,5.829715,-0.489606,0.000204,-0.000191,4.546075,2.802554,9.941609,7.955489,1,janvier

In [5]:
train.tail(1)

,insee,tH2_obs,capeinsSOL0,ciwcH20,clwcH20,ddH10_rose4,ffH10,flir1SOL0,fllat1SOL0,flsen1SOL0,flvis1SOL0,hcoulimSOL0,huH2,iwcSOL0,nbSOL0_HMoy,nH20,ntSOL0_HMoy,pMER0,rr1SOL0,rrH20,tH2,tH2_VGrad_2.100,tH2_XGrad,tH2_YGrad,tpwHPA850,ux1H10,vapcSOL0,vx1H10,ech,mois
date,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
2016-05-30,75114001,15.1,37.96799,0.0,0.0,1.0,4.787774,-36131.218648,-104907.174372,-29352.106044,3.600000e-12,634.417512,84.116919,0.0,6.808911,0.0,8.0,1008.687416,0.000033,0.0,15.530561,-1.158119,0.000501,0.001025,13.568253,4.275935,29.26325,-8.666735,1,mai

In [6]:
train.info()

<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 6167 entries, 2014-01-01 to 2016-05-30
Data columns (total 30 columns):
insee              6167 non-null int64
tH2_obs            6167 non-null float64
capeinsSOL0        5586 non-null float64
ciwcH20            6160 non-null float64
clwcH20            6048 non-null float64
ddH10_rose4        6041 non-null object
ffH10              6041 non-null float64
flir1SOL0          6160 non-null float64
fllat1SOL0         6167 non-null float64
flsen1SOL0         6160 non-null float64
flvis1SOL0         6160 non-null float64
hcoulimSOL0        6160 non-null float64
huH2               6041 non-null float64
iwcSOL0            6160 non-null float64
nbSOL0_HMoy        6160 non-null float64
nH20               5845 non-null float64
ntSOL0_HMoy        6160 non-null float64
pMER0              6027 non-null float64
rr1SOL0            6160 non-null float64
rrH20              6041 non-null float64
tH2                6041 non-null float64
tH2_VGrad_2.100    6041 non-null float64
tH2_XGrad          6041 non-null float64
tH2_YGrad          6041 non-null float64
tpwHPA850          6160 non-null float64
ux1H10             6041 non-null float64
vapcSOL0           6160 non-null float64
vx1H10             6048 non-null float64
ech                6167 non-null int64
mois               6167 non-null object
dtypes: float64(26), int64(2), object(2)
memory usage: 1.5+ MB

ddH10_rose4, mois object type => category ?  
There are missing values

In [7]:
train.describe(include='all')

,insee,tH2_obs,capeinsSOL0,ciwcH20,clwcH20,ddH10_rose4,ffH10,flir1SOL0,fllat1SOL0,flsen1SOL0,flvis1SOL0,hcoulimSOL0,huH2,iwcSOL0,nbSOL0_HMoy,nH20,ntSOL0_HMoy,pMER0,rr1SOL0,rrH20,tH2,tH2_VGrad_2.100,tH2_XGrad,tH2_YGrad,tpwHPA850,ux1H10,vapcSOL0,vx1H10,ech,mois
count,6.167000e+03,6167.000000,5586.000000,6.160000e+03,6048.000000,6041,6041.000000,6160.000000,6.167000e+03,6160.000000,6.160000e+03,6160.000000,6041.000000,6160.000000,6160.000000,5845.000000,6160.000000,6027.000000,6160.000000,6041.000000,6041.000000,6041.000000,6041.000000,6041.000000,6160.000000,6041.000000,6160.000000,6048.000000,6167.0,6167
unique,NaN,NaN,NaN,NaN,NaN,4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,12
top,NaN,NaN,NaN,NaN,NaN,4.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,janvier
freq,NaN,NaN,NaN,NaN,NaN,2044,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,651
mean,4.390000e+07,10.714788,37.366002,6.747272e-08,0.000005,NaN,3.021334,-187621.781077,-3.007864e+04,40626.427357,3.600000e-12,304.393988,82.958615,0.019749,2.194061,0.263000,4.723653,1016.782426,0.082548,0.003303,11.041032,0.985790,0.001710,0.000174,9.622448,1.207355,17.925093,0.638257,1.0,NaN
std,2.246953e+07,5.624477,104.122266,1.289975e-06,0.000034,NaN,1.910197,93786.779163,7.978076e+04,73618.358613,8.078591e-28,375.040197,11.797864,0.336138,2.905182,1.261355,3.317032,8.563395,0.486920,0.021460,5.806751,1.930998,0.002710,0.003594,4.645450,4.218907,8.050837,4.377474,0.0,NaN
min,6.088001e+06,-6.100000,0.000000,0.000000e+00,0.000000,NaN,0.008230,-503863.736917,-1.453469e+06,-224336.423922,3.600000e-12,0.466309,15.270923,0.000000,0.000000,0.000000,0.000000,982.386670,0.000000,0.000000,-6.967169,-1.794131,-0.011979,-0.017866,-3.398325,-21.681247,1.305881,-14.486823,1.0,NaN
25%,3.106900e+07,6.700000,0.000000,0.000000e+00,0.000000,NaN,1.736467,-254116.866438,-3.643746e+04,-2320.273261,3.600000e-12,46.977809,76.730183,0.000000,0.000000,0.000000,0.760056,1011.759314,0.000000,0.000000,6.883331,-0.498416,0.000138,-0.000889,6.247811,-1.192880,11.608499,-2.408628,1.0,NaN
50%,3.528100e+07,10.500000,1.029342,0.000000e+00,0.000000,NaN,2.591331,-206017.425408,-5.467513e+02,21096.272421,3.600000e-12,159.982197,85.493204,0.000000,0.351207,0.000000,6.022196,1017.029292,0.000000,0.000000,10.930386,0.354849,0.001202,0.000363,9.556014,1.139585,16.861516,0.412076,1.0,NaN
75%,6.712400e+07,14.500000,20.048593,0.000000e+00,0.000000,NaN,3.807748,-116794.746585,6.696667e+03,70471.989502,3.600000e-12,419.951200,91.789160,0.000000,4.247805,0.000000,7.995756,1022.196427,0.000000,0.000000,14.946809,2.049851,0.003035,0.001933,13.003378,3.286184,22.983955,3.279945,1.0,NaN
max,7.511400e+07,29.799999,1083.809402,4.305547e-05,0.000413,NaN,15.310204,78624.299681,9.387913e+04,641199.521351,3.600000e-12,3617.658173,99.997908,10.107500,8.000000,8.331533,8.000000,1043.259009,14.344218,0.727914,30.683831,11.169983,0.019835,0.014316,21.767814,23.799293,53.544544,22.807208,1.0,NaN

**tH2_obs** :	Observation de la température à 2 mètres in situ- au point station (prédictant)  
**capeinsSOL0**: 	Energie potentielle convective  
**ciwcH20**: 	Fraction de glace nuageuse à 20 mètres  
**clwcH20**: 	Fraction d'eau nuageuse à 20 mètres  
**ddH10_rose4**: 	Direction du vent à 10 mètres en rose4  
**ffH10**: 	Force du vent à 10 mètres en m/s  
**flir1SOL0**: 	Flux Infra-rouge en J/m2  
**fllat1SOL0**: 	Flux de chaleur latente en J/m2  
**flsen1SOL0**: 	Flux de chaleur sensible en J/m2  
**flvis1SOL0**: 	Flux visible en J/m2  
**hcoulimSOL0**: 	Hauteur de la couche limite en mètres  
**huH2**: 	Humidité 2mètres en %  
**iwcSOL0**: 	Réservoir neige kg/m2 (équivalent en eau liquide des chutes de neige)  
**nbSOL0_HMoy**: 	Nébulosité basse (moyenne sur les 6 points de grille autour de la station) (fraction en octat du ciel occulté)  
**nH20**: 	Fraction nuageuse à 20 mètres  
**ntSOL0_HMoy**: 	Nébulosité totale (moyenne sur les 6 points de grille autour de la station)  
**pMER0**: 	Pression au niveau de la mer  
**rr1SOL0**: 	Précipitation horaire au niveau du sol  
**rrH20**: 	Précipitation horaire à 20 mètres  
**tH2**: 	Température à 2 mètres du modèle AROME  
**tH2_VGrad_2.100**: 	Gradient vertical de température entre 2 mètres et 100 mètres  
**tH2_XGrad**: 	Gradient zonal de température à 2 mètres  
**tH2_YGrad**: 	Gradient méridien de température à 2 mètres  
**tpwHPA850**: 	Température potentielle au niveau 850 hPa  
**ux1H10**: 	Rafale 1 minute du vent à 10 mètres composante zonale  
**vapcSOL0**: 	Colonne de vapeur d'eau  
**vx1H10**: 	Rafale 1 minute du vent à 10 mètres composante verticale  
**ech** : 	Echéance de validité = date

# Rows with nan

In [8]:
# Total missings values by variable
pd.DataFrame(train.isnull().sum()).T

,insee,tH2_obs,capeinsSOL0,ciwcH20,clwcH20,ddH10_rose4,ffH10,flir1SOL0,fllat1SOL0,flsen1SOL0,flvis1SOL0,hcoulimSOL0,huH2,iwcSOL0,nbSOL0_HMoy,nH20,ntSOL0_HMoy,pMER0,rr1SOL0,rrH20,tH2,tH2_VGrad_2.100,tH2_XGrad,tH2_YGrad,tpwHPA850,ux1H10,vapcSOL0,vx1H10,ech,mois
0,0,0,581,7,119,126,126,7,0,7,7,7,126,7,7,322,7,140,7,126,126,126,126,126,7,126,7,119,0,0

In [15]:
for i in np.where(train.isnull().sum() == 126)[0]:
    print(np.where(np.asanyarray(pd.isnull(train.iloc[:,i]))))

(array([2653, 2654, 2655, 2656, 2657, 2658, 2659, 2660, 2661, 2662, 2663,
       2664, 2665, 2666, 2667, 2668, 2669, 2670, 2671, 2672, 2673, 2674,
       2675, 2676, 2677, 2678, 2679, 2680, 2681, 2682, 2683, 2684, 2685,
       2686, 2687, 2688, 2689, 2690, 2691, 2692, 2693, 2694, 2695, 2696,
       2697, 2698, 2699, 2700, 2701, 2702, 2703, 2704, 2705, 2706, 2707,
       2708, 2709, 2710, 2711, 2712, 2713, 2714, 2715, 2716, 2717, 2718,
       2719, 2720, 2721, 2722, 2723, 2724, 2725, 2726, 2727, 2728, 2729,
       2730, 2731, 2732, 2733, 2734, 2735, 2736, 2737, 2738, 2739, 2740,
       2741, 2742, 2743, 2744, 2745, 2746, 2747, 2748, 2749, 2750, 2751,
       2752, 2753, 2754, 2755, 2756, 2757, 2758, 2759, 2760, 2761, 2762,
       2763, 2764, 2765, 2766, 2767, 2768, 2769, 2770, 2771, 4627, 4628,
       4629, 4630, 4631, 4632, 4633]),)
(array([2653, 2654, 2655, 2656, 2657, 2658, 2659, 2660, 2661, 2662, 2663,
       2664, 2665, 2666, 2667, 2668, 2669, 2670, 2671, 2672, 2673, 2674,
       2675, 2676, 2677, 2678, 2679, 2680, 2681, 2682, 2683, 2684, 2685,
       2686, 2687, 2688, 2689, 2690, 2691, 2692, 2693, 2694, 2695, 2696,
       2697, 2698, 2699, 2700, 2701, 2702, 2703, 2704, 2705, 2706, 2707,
       2708, 2709, 2710, 2711, 2712, 2713, 2714, 2715, 2716, 2717, 2718,
       2719, 2720, 2721, 2722, 2723, 2724, 2725, 2726, 2727, 2728, 2729,
       2730, 2731, 2732, 2733, 2734, 2735, 2736, 2737, 2738, 2739, 2740,
       2741, 2742, 2743, 2744, 2745, 2746, 2747, 2748, 2749, 2750, 2751,
       2752, 2753, 2754, 2755, 2756, 2757, 2758, 2759, 2760, 2761, 2762,
       2763, 2764, 2765, 2766, 2767, 2768, 2769, 2770, 2771, 4627, 4628,
       4629, 4630, 4631, 4632, 4633]),)
(array([2653, 2654, 2655, 2656, 2657, 2658, 2659, 2660, 2661, 2662, 2663,
       2664, 2665, 2666, 2667, 2668, 2669, 2670, 2671, 2672, 2673, 2674,
       2675, 2676, 2677, 2678, 2679, 2680, 2681, 2682, 2683, 2684, 2685,
       2686, 2687, 2688, 2689, 2690, 2691, 2692, 2693, 2694, 2695, 2696,
       2697, 2698, 2699, 2700, 2701, 2702, 2703, 2704, 2705, 2706, 2707,
       2708, 2709, 2710, 2711, 2712, 2713, 2714, 2715, 2716, 2717, 2718,
       2719, 2720, 2721, 2722, 2723, 2724, 2725, 2726, 2727, 2728, 2729,
       2730, 2731, 2732, 2733, 2734, 2735, 2736, 2737, 2738, 2739, 2740,
       2741, 2742, 2743, 2744, 2745, 2746, 2747, 2748, 2749, 2750, 2751,
       2752, 2753, 2754, 2755, 2756, 2757, 2758, 2759, 2760, 2761, 2762,
       2763, 2764, 2765, 2766, 2767, 2768, 2769, 2770, 2771, 4627, 4628,
       4629, 4630, 4631, 4632, 4633]),)
(array([2653, 2654, 2655, 2656, 2657, 2658, 2659, 2660, 2661, 2662, 2663,
       2664, 2665, 2666, 2667, 2668, 2669, 2670, 2671, 2672, 2673, 2674,
       2675, 2676, 2677, 2678, 2679, 2680, 2681, 2682, 2683, 2684, 2685,
       2686, 2687, 2688, 2689, 2690, 2691, 2692, 2693, 2694, 2695, 2696,
       2697, 2698, 2699, 2700, 2701, 2702, 2703, 2704, 2705, 2706, 2707,
       2708, 2709, 2710, 2711, 2712, 2713, 2714, 2715, 2716, 2717, 2718,
       2719, 2720, 2721, 2722, 2723, 2724, 2725, 2726, 2727, 2728, 2729,
       2730, 2731, 2732, 2733, 2734, 2735, 2736, 2737, 2738, 2739, 2740,
       2741, 2742, 2743, 2744, 2745, 2746, 2747, 2748, 2749, 2750, 2751,
       2752, 2753, 2754, 2755, 2756, 2757, 2758, 2759, 2760, 2761, 2762,
       2763, 2764, 2765, 2766, 2767, 2768, 2769, 2770, 2771, 4627, 4628,
       4629, 4630, 4631, 4632, 4633]),)
(array([2653, 2654, 2655, 2656, 2657, 2658, 2659, 2660, 2661, 2662, 2663,
       2664, 2665, 2666, 2667, 2668, 2669, 2670, 2671, 2672, 2673, 2674,
       2675, 2676, 2677, 2678, 2679, 2680, 2681, 2682, 2683, 2684, 2685,
       2686, 2687, 2688, 2689, 2690, 2691, 2692, 2693, 2694, 2695, 2696,
       2697, 2698, 2699, 2700, 2701, 2702, 2703, 2704, 2705, 2706, 2707,
       2708, 2709, 2710, 2711, 2712, 2713, 2714, 2715, 2716, 2717, 2718,
       2719, 2720, 2721, 2722, 2723, 2724, 2725, 2726, 2727, 2728, 2729,
       2730, 2731, 2732, 2733, 2734, 2735, 2736, 2737, 2738, 2739, 2740,
       2741, 2742, 2743, 2744, 2745, 2746, 2747, 2748, 2749, 2750, 2751,
       2752, 2753, 2754, 2755, 2756, 2757, 2758, 2759, 2760, 2761, 2762,
       2763, 2764, 2765, 2766, 2767, 2768, 2769, 2770, 2771, 4627, 4628,
       4629, 4630, 4631, 4632, 4633]),)
(array([2653, 2654, 2655, 2656, 2657, 2658, 2659, 2660, 2661, 2662, 2663,
       2664, 2665, 2666, 2667, 2668, 2669, 2670, 2671, 2672, 2673, 2674,
       2675, 2676, 2677, 2678, 2679, 2680, 2681, 2682, 2683, 2684, 2685,
       2686, 2687, 2688, 2689, 2690, 2691, 2692, 2693, 2694, 2695, 2696,
       2697, 2698, 2699, 2700, 2701, 2702, 2703, 2704, 2705, 2706, 2707,
       2708, 2709, 2710, 2711, 2712, 2713, 2714, 2715, 2716, 2717, 2718,
       2719, 2720, 2721, 2722, 2723, 2724, 2725, 2726, 2727, 2728, 2729,
       2730, 2731, 2732, 2733, 2734, 2735, 2736, 2737, 2738, 2739, 2740,
       2741, 2742, 2743, 2744, 2745, 2746, 2747, 2748, 2749, 2750, 2751,
       2752, 2753, 2754, 2755, 2756, 2757, 2758, 2759, 2760, 2761, 2762,
       2763, 2764, 2765, 2766, 2767, 2768, 2769, 2770, 2771, 4627, 4628,
       4629, 4630, 4631, 4632, 4633]),)
(array([2653, 2654, 2655, 2656, 2657, 2658, 2659, 2660, 2661, 2662, 2663,
       2664, 2665, 2666, 2667, 2668, 2669, 2670, 2671, 2672, 2673, 2674,
       2675, 2676, 2677, 2678, 2679, 2680, 2681, 2682, 2683, 2684, 2685,
       2686, 2687, 2688, 2689, 2690, 2691, 2692, 2693, 2694, 2695, 2696,
       2697, 2698, 2699, 2700, 2701, 2702, 2703, 2704, 2705, 2706, 2707,
       2708, 2709, 2710, 2711, 2712, 2713, 2714, 2715, 2716, 2717, 2718,
       2719, 2720, 2721, 2722, 2723, 2724, 2725, 2726, 2727, 2728, 2729,
       2730, 2731, 2732, 2733, 2734, 2735, 2736, 2737, 2738, 2739, 2740,
       2741, 2742, 2743, 2744, 2745, 2746, 2747, 2748, 2749, 2750, 2751,
       2752, 2753, 2754, 2755, 2756, 2757, 2758, 2759, 2760, 2761, 2762,
       2763, 2764, 2765, 2766, 2767, 2768, 2769, 2770, 2771, 4627, 4628,
       4629, 4630, 4631, 4632, 4633]),)
(array([2653, 2654, 2655, 2656, 2657, 2658, 2659, 2660, 2661, 2662, 2663,
       2664, 2665, 2666, 2667, 2668, 2669, 2670, 2671, 2672, 2673, 2674,
       2675, 2676, 2677, 2678, 2679, 2680, 2681, 2682, 2683, 2684, 2685,
       2686, 2687, 2688, 2689, 2690, 2691, 2692, 2693, 2694, 2695, 2696,
       2697, 2698, 2699, 2700, 2701, 2702, 2703, 2704, 2705, 2706, 2707,
       2708, 2709, 2710, 2711, 2712, 2713, 2714, 2715, 2716, 2717, 2718,
       2719, 2720, 2721, 2722, 2723, 2724, 2725, 2726, 2727, 2728, 2729,
       2730, 2731, 2732, 2733, 2734, 2735, 2736, 2737, 2738, 2739, 2740,
       2741, 2742, 2743, 2744, 2745, 2746, 2747, 2748, 2749, 2750, 2751,
       2752, 2753, 2754, 2755, 2756, 2757, 2758, 2759, 2760, 2761, 2762,
       2763, 2764, 2765, 2766, 2767, 2768, 2769, 2770, 2771, 4627, 4628,
       4629, 4630, 4631, 4632, 4633]),)
(array([2653, 2654, 2655, 2656, 2657, 2658, 2659, 2660, 2661, 2662, 2663,
       2664, 2665, 2666, 2667, 2668, 2669, 2670, 2671, 2672, 2673, 2674,
       2675, 2676, 2677, 2678, 2679, 2680, 2681, 2682, 2683, 2684, 2685,
       2686, 2687, 2688, 2689, 2690, 2691, 2692, 2693, 2694, 2695, 2696,
       2697, 2698, 2699, 2700, 2701, 2702, 2703, 2704, 2705, 2706, 2707,
       2708, 2709, 2710, 2711, 2712, 2713, 2714, 2715, 2716, 2717, 2718,
       2719, 2720, 2721, 2722, 2723, 2724, 2725, 2726, 2727, 2728, 2729,
       2730, 2731, 2732, 2733, 2734, 2735, 2736, 2737, 2738, 2739, 2740,
       2741, 2742, 2743, 2744, 2745, 2746, 2747, 2748, 2749, 2750, 2751,
       2752, 2753, 2754, 2755, 2756, 2757, 2758, 2759, 2760, 2761, 2762,
       2763, 2764, 2765, 2766, 2767, 2768, 2769, 2770, 2771, 4627, 4628,
       4629, 4630, 4631, 4632, 4633]),)

Same row location for missing vals for these variables

In [20]:
# Rows with missing val
np.where(train.isnull().sum(axis=1).values > 0)[0]

array([ 539,  540,  541,  542,  543,  544,  545,  546,  547,  548,  549,
        550,  551,  552,  553,  554,  555,  556,  557,  558,  559,  560,
        561,  562,  563,  564,  565,  566,  567,  568,  569,  570,  571,
        572,  573,  574,  575,  576,  577,  578,  579,  580,  581,  582,
        583,  584,  585,  586,  587,  588,  589,  590,  591,  592,  593,
        594,  595,  596,  597,  598,  599,  600,  601,  602,  603,  604,
        605,  606,  607,  608,  609,  610,  611,  612,  613,  614,  615,
        616,  617,  618,  619,  620,  621,  622,  623,  624,  625,  626,
        627,  628,  629,  819,  820,  821,  822,  823,  824,  825,  826,
        827,  828,  829,  830,  831,  832,  833,  834,  835,  836,  837,
        838,  839, 1540, 1541, 1542, 1543, 1544, 1545, 1546, 1547, 1548,
       1549, 1550, 1551, 1552, 1553, 1554, 1555, 1556, 1557, 1558, 1559,
       1560, 1561, 1562, 1563, 1564, 1565, 1566, 1567, 1568, 1569, 1570,
       1571, 1572, 1573, 1574, 1575, 1576, 1577, 1578, 1579, 1580, 1581,
       1582, 1583, 1584, 1585, 1586, 1587, 1588, 1589, 1590, 1591, 1592,
       1593, 1594, 1595, 1596, 1597, 1598, 1599, 1600, 1601, 1602, 1603,
       1604, 1605, 1606, 1607, 1608, 1609, 1610, 1611, 1612, 1613, 1614,
       1615, 1616, 1617, 1618, 1619, 1620, 1621, 1622, 1623, 1624, 1625,
       1626, 1627, 1628, 1629, 1630, 1631, 1632, 1633, 1634, 1635, 1636,
       1637, 1638, 1639, 1640, 1641, 1642, 1643, 1644, 1645, 1646, 1647,
       1648, 1649, 1650, 1651, 1652, 1653, 1654, 1655, 1656, 1657, 1658,
       1659, 1660, 1661, 1662, 1663, 1664, 1665, 1666, 1667, 1668, 1669,
       1670, 1671, 1672, 1673, 1674, 1675, 1676, 1677, 1678, 1679, 1680,
       1681, 1682, 1683, 1684, 1685, 1686, 1687, 1688, 1689, 1690, 1691,
       1692, 1693, 1694, 1695, 1696, 1697, 1698, 1699, 1700, 2023, 2024,
       2025, 2026, 2027, 2028, 2029, 2030, 2031, 2032, 2033, 2034, 2035,
       2036, 2037, 2038, 2039, 2040, 2041, 2042, 2043, 2044, 2045, 2046,
       2047, 2048, 2049, 2050, 2051, 2052, 2053, 2054, 2055, 2056, 2057,
       2058, 2059, 2060, 2061, 2062, 2063, 2064, 2065, 2066, 2067, 2068,
       2069, 2070, 2071, 2072, 2073, 2074, 2075, 2076, 2077, 2078, 2079,
       2080, 2081, 2082, 2083, 2084, 2085, 2086, 2087, 2088, 2089, 2090,
       2091, 2092, 2093, 2094, 2095, 2096, 2097, 2098, 2099, 2100, 2101,
       2102, 2103, 2104, 2105, 2106, 2107, 2108, 2109, 2110, 2111, 2112,
       2113, 2114, 2115, 2116, 2117, 2118, 2119, 2120, 2121, 2122, 2123,
       2124, 2125, 2126, 2127, 2653, 2654, 2655, 2656, 2657, 2658, 2659,
       2660, 2661, 2662, 2663, 2664, 2665, 2666, 2667, 2668, 2669, 2670,
       2671, 2672, 2673, 2674, 2675, 2676, 2677, 2678, 2679, 2680, 2681,
       2682, 2683, 2684, 2685, 2686, 2687, 2688, 2689, 2690, 2691, 2692,
       2693, 2694, 2695, 2696, 2697, 2698, 2699, 2700, 2701, 2702, 2703,
       2704, 2705, 2706, 2707, 2708, 2709, 2710, 2711, 2712, 2713, 2714,
       2715, 2716, 2717, 2718, 2719, 2720, 2721, 2722, 2723, 2724, 2725,
       2726, 2727, 2728, 2729, 2730, 2731, 2732, 2733, 2734, 2735, 2736,
       2737, 2738, 2739, 2740, 2741, 2742, 2743, 2744, 2745, 2746, 2747,
       2748, 2749, 2750, 2751, 2752, 2753, 2754, 2755, 2756, 2757, 2758,
       2759, 2760, 2761, 2762, 2763, 2764, 2765, 2766, 2767, 2768, 2769,
       2770, 2771, 2849, 2850, 2851, 2852, 2853, 2854, 2855, 2856, 2857,
       2858, 2859, 2860, 2861, 2862, 2863, 2864, 2865, 2866, 2867, 2868,
       2869, 2870, 2871, 2872, 2873, 2874, 2875, 2876, 2877, 2878, 2879,
       2880, 2881, 2882, 2883, 2884, 2885, 2886, 2887, 2888, 2889, 2890,
       2891, 2892, 2893, 2894, 2895, 2896, 2897, 2898, 2899, 2900, 2901,
       2902, 2903, 2904, 2905, 2906, 2907, 2908, 2909, 2910, 2911, 2912,
       2913, 2914, 2915, 2916, 2917, 2918, 2919, 2920, 2921, 2922, 2923,
       2924, 2925, 2926, 2927, 2928, 2929, 2930, 2931, 2932, 2933, 2934,
       2935, 2936, 2937, 2938, 2939, 2940, 2941, 2942, 2943, 2944, 2945,
       2946, 2947, 2948, 2949, 2950, 2951, 2952, 2953, 2954, 2955, 2956,
       2957, 2958, 2959, 2960, 2961, 2962, 2963, 2964, 2965, 2966, 2967,
       2968, 2969, 2970, 2971, 2972, 2973, 2974, 2975, 2976, 2977, 2978,
       2979, 2980, 2981, 3409, 3410, 3411, 3412, 3413, 3414, 3415, 3416,
       3417, 3418, 3419, 3420, 3421, 3422, 3423, 3424, 3425, 3426, 3427,
       3428, 3429, 3430, 3431, 3432, 3433, 3434, 3435, 3436, 3437, 3438,
       3439, 3440, 3441, 3442, 3443, 3444, 3445, 3446, 3447, 3448, 3449,
       3450, 3451, 3452, 3453, 3454, 3455, 3456, 3457, 3458, 3459, 3460,
       3461, 3462, 3463, 3464, 3465, 3466, 3467, 3468, 3469, 3470, 3471,
       3472, 3473, 3474, 3475, 3476, 3477, 3478, 3479, 3480, 3481, 3482,
       3483, 3484, 3485, 3486, 3487, 3488, 3489, 3490, 3491, 3492, 3493,
       3494, 3495, 3496, 3497, 3498, 3499, 3500, 3501, 3502, 3503, 3504,
       3505, 3506, 3507, 3508, 3509, 3510, 3511, 3512, 3513, 3514, 3515,
       3516, 3517, 3518, 3519, 3520, 3521, 3522, 3523, 3524, 3525, 3526,
       3527, 3528, 3529, 3530, 3531, 3532, 3533, 3534, 3535, 3536, 3537,
       3538, 3539, 3540, 3541, 3542, 3543, 3544, 3545, 3546, 3547, 3548,
       3549, 3550, 3551, 3552, 3553, 3554, 3555, 3556, 3557, 3558, 3559,
       3560, 3561, 3562, 3563, 3564, 3565, 3566, 3567, 3568, 3569, 3570,
       3571, 3572, 3573, 3574, 3575, 3576, 3577, 3578, 3579, 3580, 3581,
       3582, 3583, 3584, 3585, 3586, 3587, 3588, 3589, 3590, 3591, 3592,
       3593, 3594, 3595, 3596, 3597, 3598, 3599, 3600, 3601, 3602, 3603,
       3604, 3605, 3606, 3607, 3608, 3609, 3610, 3611, 4627, 4628, 4629,
       4630, 4631, 4632, 4633])

In [11]:
# Coordinate of missing values
np.where(np.asanyarray(pd.isnull(train)))

(array([ 539,  540,  541, ..., 4633, 4633, 4633]),
 array([ 2,  2,  2, ..., 25, 26, 27]))

Lets have a look to 1 row

In [49]:
pd.DataFrame(train.iloc[2653-7*3,:]).T

,insee,tH2_obs,capeinsSOL0,ciwcH20,clwcH20,ddH10_rose4,ffH10,flir1SOL0,fllat1SOL0,flsen1SOL0,flvis1SOL0,hcoulimSOL0,huH2,iwcSOL0,nbSOL0_HMoy,nH20,ntSOL0_HMoy,pMER0,rr1SOL0,rrH20,tH2,tH2_VGrad_2.100,tH2_XGrad,tH2_YGrad,tpwHPA850,ux1H10,vapcSOL0,vx1H10,ech,mois
2015-01-12,6088001,8.6,0.0640884,0,0,4.0,3.52355,-369955,-120083,-19096.3,3.6e-12,367.236,69.2346,0,0,0,0,1027.16,0,0,12.7426,0.0238568,0.00212395,-0.00562426,7.18519,3.71358,9.45647,-3.8209,1,janvier

### Lets see if one can interpolate the missing values

In [31]:
for i in range(1,12):
    print(train.index[2653-7*i], 
          '- tH2 val : {} for station {}'.format(train.tH2[2653-7*i], train.insee[2653-7*i]))
print('interpolate : {}'.format(train.tH2.interpolate()[2653]))

2015-01-14 00:00:00 - tH2 val : 10.0729816897 for station 6088001
2015-01-13 00:00:00 - tH2 val : 10.2807315976 for station 6088001
2015-01-12 00:00:00 - tH2 val : 12.7425761237 for station 6088001
2015-01-11 00:00:00 - tH2 val : 11.9128324598 for station 6088001
2015-01-10 00:00:00 - tH2 val : 12.5950243749 for station 6088001
2015-01-09 00:00:00 - tH2 val : 11.5817210114 for station 6088001
2015-01-08 00:00:00 - tH2 val : 12.5677185878 for station 6088001
2015-01-07 00:00:00 - tH2 val : 10.9514668153 for station 6088001
2015-01-06 00:00:00 - tH2 val : 10.8505156723 for station 6088001
2015-01-05 00:00:00 - tH2 val : 12.2458668095 for station 6088001
2015-01-04 00:00:00 - tH2 val : 12.2941543056 for station 6088001
interpolate : 7.47757626733

In [22]:
for i in range(1,20):
    print(train.tH2[2653+7*i])

nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
6.99378191254
8.54323770763
7.40550798924

In [45]:
gb_cities = train.groupby('insee')
print(gb_cities.tH2.resample('W').median()[6088001]['2015-01'])
# print(gb_cities.index.week[2653-7*3])

date
2015-01-04     9.708945
2015-01-11    11.912832
2015-01-18    10.280732
2015-01-25          NaN
Freq: W-SUN, Name: tH2, dtype: float64

Seems to work when replacing with median with respect to insee

### Difficile d'interpoler (ici pour capeinsSOL0)

In [24]:
for i in range(1,5):
    print(train.index[4627-7*i], 
          ' - flir1SOL0 val : {} for station {}'.format(train.flir1SOL0[4627-7*i], train.insee[4627-7*i]))
print('interpolate : {}'.format(train.flir1SOL0.interpolate()[4627]))
for i in range(1,5):
    print(train.flir1SOL0[4627+7*i])

2015-10-23 00:00:00  - flir1SOL0 val : -300419.068928 for station 6088001
2015-10-22 00:00:00  - flir1SOL0 val : -359352.081127 for station 6088001
2015-10-21 00:00:00  - flir1SOL0 val : -287801.884945 for station 6088001
2015-10-20 00:00:00  - flir1SOL0 val : -321568.307394 for station 6088001
interpolate : -216105.452204
-300294.133067
-233957.359109
-147976.02331
-99174.0422456

### Ici ca marche. A explorer

### Replace na val en utilisant le groupby. Faire des stats par city

https://machinelearningmastery.com/time-series-data-visualization-with-python/

In [16]:
# groupby_city = train.groupby('insee')
# groupby_city.capeinsSOL0.apply(pd.Series.interpolate)

## Missing values by file

In [17]:
df_miss_val = pd.DataFrame(columns=train.columns)
for i in range(1,37):
    tmp =pd.read_csv(data_path + 'train_' + str(i) + '.csv', 
                     header=0, delimiter=";",decimal=',',
                     parse_dates=['date'], index_col='date')
    df_miss_val = pd.concat([df_miss_val, pd.DataFrame(tmp.isnull().sum()).T], axis=0 )
df_miss_val

,insee,tH2_obs,capeinsSOL0,ciwcH20,clwcH20,ddH10_rose4,ffH10,flir1SOL0,fllat1SOL0,flsen1SOL0,flvis1SOL0,hcoulimSOL0,huH2,iwcSOL0,nbSOL0_HMoy,nH20,ntSOL0_HMoy,pMER0,rr1SOL0,rrH20,tH2,tH2_VGrad_2.100,tH2_XGrad,tH2_YGrad,tpwHPA850,ux1H10,vapcSOL0,vx1H10,ech,mois
0,0,0,581,7,119,126,126,7,0,7,7,7,126,7,7,322,7,140,7,126,126,126,126,126,7,126,7,119,0,0
0,0,0,581,7,126,126,126,14,14,14,14,7,126,7,7,329,7,140,7,126,119,119,119,119,7,126,7,126,0,0
0,0,0,581,7,119,126,126,14,7,14,14,0,126,7,7,329,0,140,7,126,126,126,126,126,7,126,7,126,0,0
0,0,0,581,7,126,126,126,14,7,14,14,7,126,7,7,329,7,140,7,126,126,126,126,126,7,126,7,126,0,0
0,0,0,581,7,119,126,126,14,7,14,14,7,126,7,7,329,7,140,7,119,126,126,126,126,0,126,7,126,0,0
0,0,0,588,0,126,126,126,14,10,14,14,7,126,7,7,329,0,140,7,126,126,126,126,126,7,126,7,126,0,0
0,0,0,588,7,119,126,126,14,7,15,14,7,126,0,7,329,7,140,7,119,126,126,126,126,7,126,7,126,0,0
0,0,0,588,7,126,126,126,14,7,14,14,7,119,7,7,329,7,133,7,126,126,126,126,126,7,126,7,126,0,0
0,0,0,588,0,126,126,126,14,7,14,14,7,126,7,7,336,7,133,7,119,126,126,126,126,7,126,7,126,0,0
0,0,3,588,7,126,126,126,14,7,15,14,7,119,7,0,336,7,133,7,119,126,126,126,126,7,126,7,126,0,0
0,0,2,595,0,119,126,126,14,7,14,14,7,126,0,7,336,0,133,7,119,126,126,126,126,7,126,7,126,0,0
0,0,2,595,7,119,126,126,14,7,7,14,7,126,7,7,336,7,133,7,119,126,126,126,126,7,126,7,126,0,0
0,0,2,602,0,119,126,126,14,7,7,14,7,126,7,7,336,7,133,7,119,126,126,126,126,7,126,0,126,0,0
0,0,2,602,0,126,126,126,14,7,7,7,7,126,7,7,336,7,133,7,126,126,126,126,126,0,126,7,126,0,0
0,0,1,602,7,119,126,126,14,7,7,7,7,119,7,7,336,7,133,7,119,126,126,126,126,7,126,7,126,0,0
0,0,1,602,0,126,126,126,14,7,7,7,7,126,7,7,336,7,133,7,126,126,126,126,126,7,126,7,126,0,0
0,0,2,602,0,119,126,126,14,7,7,7,7,126,7,7,336,7,133,7,126,126,126,126,126,7,126,7,126,0,0
0,0,0,609,0,126,126,126,14,7,7,7,7,126,7,7,329,7,126,7,126,126,126,126,126,0,126,7,126,0,0
0,0,2,609,7,126,126,126,14,7,7,7,7,126,0,7,336,7,133,7,119,126,126,126,126,7,126,7,126,0,0
0,0,0,609,0,126,126,126,14,8,7,7,7,126,7,0,336,7,133,7,126,126,126,126,126,7,126,7,126,0,0
0,0,0,609,0,126,126,126,14,7,7,7,7,126,0,7,336,7,133,7,126,126,126,126,126,7,126,7,126,0,0
0,0,0,609,7,126,126,126,14,7,7,7,7,126,7,7,336,7,126,7,126,126,126,126,126,7,126,7,126,0,0
0,0,0,609,7,119,126,126,7,7,7,7,7,126,7,7,336,7,133,7,119,119,126,119,119,7,126,7,126,0,0
0,0,0,616,7,119,126,126,7,7,7,7,7,126,7,7,329,7,133,7,126,126,126,126,126,7,126,7,126,0,0
0,0,0,616,7,126,126,126,7,7,7,7,0,126,7,7,336,7,133,7,126,126,126,126,126,7,126,7,126,0,0
0,0,0,609,7,126,126,126,7,7,7,7,7,126,7,7,336,7,133,7,126,126,126,126,126,7,126,7,126,0,0
0,0,0,616,7,126,126,126,7,7,7,7,7,126,7,7,329,7,133,7,126,126,126,126,126,7,126,7,126,0,0
0,0,0,609,7,126,126,126,7,7,7,7,0,126,7,7,336,7,133,7,126,126,126,126,126,7,126,7,126,0,0
0,0,0,609,7,126,126,126,7,7,7,7,7,126,0,7,336,7,133,7,126,126,126,126,126,7,126,7,126,0,0
0,0,0,616,0,126,126,126,7,7,7,7,0,126,7,7,336,7,133,7,119,126,126,126,126,7,126,0,126,0,0
0,0,0,133,140,126,133,133,140,147,147,140,133,133,133,133,133,133,126,140,133,133,133,133,133,140,133,133,133,0,0
0,0,0,133,140,126,133,133,133,140,140,133,133,133,133,133,133,133,126,133,133,133,133,133,133,140,133,133,133,0,0
0,0,0,133,140,133,133,133,133,140,140,133,126,133,133,133,133,133,133,133,126,133,133,133,133,140,133,133,133,0,0
0,0,1,133,140,133,133,133,133,140,140,133,133,133,133,133,133,133,133,133,133,133,133,133,133,133,133,133,133,0,0
0,0,1,133,140,133,133,133,133,140,140,133,133,133,133,126,133,133,133,133,133,133,133,133,133,140,133,133,126,0,0
0,0,1,133,140,126,133,133,133,140,140,133,133,133,133,133,126,133,133,133,126,126,126,126,126,140,133,133,133,0,0

Liens entre: 
    - ddH10_rose4 et ffH10
    - tH2, tH2_VGrad_2.100, tH2_XGrad, tH2_YGrad

# Link between temp and ech

idée de Grégoire

## Data processing
Stack data

In [57]:
from os import listdir

temp_ech = None
cols = ['date', 'insee', 'tH2_obs', 'tH2', 'ech']
for file_ in listdir(data_path):
    if temp_ech is None:
        temp_ech = pd.read_csv(data_path + file_, header=0, 
                               delimiter=";",decimal=',',parse_dates=['date'], index_col='date', usecols=cols)
    else:
        temp_ech = pd.concat([temp_ech, 
                              pd.read_csv(data_path + file_, header=0, delimiter=";",decimal=',', 
                                          parse_dates=['date'], index_col='date', usecols=cols
                                         )])
# train.to_csv(data_path + "train.csv", sep=';', index=False)
temp_ech.sort_values(['insee', 'ech'], ascending=[True, True], inplace=True)
temp_ech.head(8)

              insee  tH2_obs        tH2  ech
date
2014-01-01  6088001      5.5   9.034338    1
2014-01-02  6088001      7.9  10.600003    1
2014-01-03  6088001      9.1  12.007224    1
2014-01-04  6088001     11.3  11.933810    1
2014-01-05  6088001     11.2  12.305508    1
2014-01-06  6088001      8.0  11.695416    1
2014-01-07  6088001      8.4  11.552058    1
2014-01-08  6088001     10.3  12.796752    1

## Analysis

In [59]:
print(max(temp_ech.index)-min(temp_ech.index))
temp_ech['2014-01-01']

880 days 00:00:00

               insee  tH2_obs        tH2  ech
date
2014-01-01   6088001      5.5   9.034338    1
2014-01-01   6088001      5.4   8.153351    2
2014-01-01   6088001      5.1   8.402343    3
2014-01-01   6088001      4.7   8.245682    4
2014-01-01   6088001      4.7   8.514988    5
2014-01-01   6088001      4.7   9.015853    6
2014-01-01   6088001      4.8   9.179396    7
2014-01-01   6088001      5.3   9.562431    8
2014-01-01   6088001      6.2  10.131776    9
2014-01-01   6088001      7.4  10.439922   10
2014-01-01   6088001     10.0  11.069077   11
2014-01-01   6088001     10.0  11.699109   12
2014-01-01   6088001     10.3  12.153840   13
2014-01-01   6088001     10.6  12.464955   14
2014-01-01   6088001      9.8  12.101505   15
2014-01-01   6088001      8.4  12.021394   16
2014-01-01   6088001      8.6  11.785885   17
2014-01-01   6088001      7.8  11.401471   18
2014-01-01   6088001      7.7  11.205267   19
2014-01-01   6088001      7.9  11.167496   20
2014-01-01   6088001      8.1  11.227059   21
2014-01-01   6088001      7.8  11.187069   22
2014-01-01   6088001      8.0  11.142321   23
2014-01-01   6088001      8.2  11.024646   24
2014-01-01   6088001      7.9  10.973166   25
2014-01-01   6088001      7.9  10.941004   26
2014-01-01   6088001      8.2  11.033950   27
2014-01-01   6088001      8.0  10.925451   28
2014-01-01   6088001      7.8  11.262741   29
2014-01-01   6088001      7.8  11.657800   30
...              ...      ...        ...  ...
2014-01-01  75114001      7.0   7.208069    1
2014-01-01  75114001      6.9   7.282375    2
2014-01-01  75114001      7.2   7.424495    3
2014-01-01  75114001      7.0   6.700273    4
2014-01-01  75114001      7.0   6.784263    5
2014-01-01  75114001      7.0   7.359250    6
2014-01-01  75114001      7.1   7.147274    7
2014-01-01  75114001      7.3   6.889038    8
2014-01-01  75114001      7.7   6.962505    9
2014-01-01  75114001      8.1   7.575566   10
2014-01-01  75114001      8.7   8.255433   11
2014-01-01  75114001      9.1   8.632080   12
2014-01-01  75114001      9.3   9.289964   13
2014-01-01  75114001      9.8   9.621031   14
2014-01-01  75114001     10.4   9.844250   15
2014-01-01  75114001     10.7  10.010461   16
2014-01-01  75114001     10.4   9.981056   17
2014-01-01  75114001      9.7   9.821576   18
2014-01-01  75114001      9.5   9.400470   19
2014-01-01  75114001      9.5   9.273802   20
2014-01-01  75114001     10.3   9.455015   21
2014-01-01  75114001     10.3   9.702389   22
2014-01-01  75114001     10.4  10.003702   23
2014-01-01  75114001     10.8   9.940145   24
2014-01-01  75114001     10.8  10.317167   25
2014-01-01  75114001     10.9   9.685958   26
2014-01-01  75114001      9.5  10.071367   27
2014-01-01  75114001      9.6  10.283924   28
2014-01-01  75114001     10.4   9.272826   29
2014-01-01  75114001     10.3   9.153009   30

[210 rows x 4 columns]

On peut voir que quand temp à n+1 with ech=1 == temp à n with ech=25 but not true with other cols

Dealing with missing val :  
https://gallery.cortanaintelligence.com/Experiment/Methods-for-handling-missing-values-1