idée de Grégoire

In [13]:
import pandas as pd
import numpy as np
import sys
sys.path.append('../')
data_path = '../data/raw/'

## Data processing
Stack data

In [16]:
from os import listdir

cols = ['date', 'insee', 'tH2_obs', 'tH2', 'ech']
temp_ech = None
for file_ in listdir(data_path):
    if temp_ech is None:
        temp_ech = pd.read_csv(data_path + file_, header=0, 
                               delimiter=";",decimal=',',parse_dates=['date'], index_col='date', usecols=cols)
    else:
        temp_ech = pd.concat([temp_ech, 
                              pd.read_csv(data_path + file_, header=0, delimiter=";",decimal=',', 
                                          parse_dates=['date'], index_col='date', usecols=cols
                                         )])
# train.to_csv(data_path + "train.csv", sep=';', index=False)
temp_ech.sort_values(['insee', 'ech'], ascending=[True, True], inplace=True)

In [69]:
temp_ech[temp_ech['insee'] == 6088001]['2014-01-01':'2014-01-02'].head(55)

              insee  tH2_obs        tH2  ech
date
2014-01-01  6088001      5.5   9.034338    1
2014-01-02  6088001      7.9  10.600003    1
2014-01-01  6088001      5.4   8.153351    2
2014-01-02  6088001      7.9  10.960896    2
2014-01-01  6088001      5.1   8.402343    3
2014-01-02  6088001      8.2  11.138946    3
2014-01-01  6088001      4.7   8.245682    4
2014-01-02  6088001      8.0  11.596869    4
2014-01-01  6088001      4.7   8.514988    5
2014-01-02  6088001      7.8  11.656879    5
2014-01-01  6088001      4.7   9.015853    6
2014-01-02  6088001      7.8  11.602699    6
2014-01-01  6088001      4.8   9.179396    7
2014-01-02  6088001      7.8  11.420617    7
2014-01-01  6088001      5.3   9.562431    8
2014-01-02  6088001      8.1  11.202605    8
2014-01-01  6088001      6.2  10.131776    9
2014-01-02  6088001      8.5  10.722181    9
2014-01-01  6088001      7.4  10.439922   10
2014-01-02  6088001      8.8  10.866335   10
2014-01-01  6088001     10.0  11.069077   11
2014-01-02  6088001      9.3  10.894554   11
2014-01-01  6088001     10.0  11.699109   12
2014-01-02  6088001     10.1  11.172581   12
2014-01-01  6088001     10.3  12.153840   13
2014-01-02  6088001     10.2  11.395618   13
2014-01-01  6088001     10.6  12.464955   14
2014-01-02  6088001     10.0  11.708865   14
2014-01-01  6088001      9.8  12.101505   15
2014-01-02  6088001     10.4  11.905974   15
2014-01-01  6088001      8.4  12.021394   16
2014-01-02  6088001      9.9  11.868503   16
2014-01-01  6088001      8.6  11.785885   17
2014-01-02  6088001      9.8  11.671897   17
2014-01-01  6088001      7.8  11.401471   18
2014-01-02  6088001      9.7  11.621490   18
2014-01-01  6088001      7.7  11.205267   19
2014-01-02  6088001      9.5  11.616333   19
2014-01-01  6088001      7.9  11.167496   20
2014-01-02  6088001      9.6  11.634611   20
2014-01-01  6088001      8.1  11.227059   21
2014-01-02  6088001      9.3  11.540038   21
2014-01-01  6088001      7.8  11.187069   22
2014-01-02  6088001      9.0  11.719456   22
2014-01-01  6088001      8.0  11.142321   23
2014-01-02  6088001      8.8  11.916298   23
2014-01-01  6088001      8.2  11.024646   24
2014-01-02  6088001      9.0  11.905991   24
2014-01-01  6088001      7.9  10.973166   25
2014-01-02  6088001      9.1  11.990020   25
2014-01-01  6088001      7.9  10.941004   26
2014-01-02  6088001      8.6  12.003405   26
2014-01-01  6088001      8.2  11.033950   27
2014-01-02  6088001      8.5  11.792295   27
2014-01-01  6088001      8.0  10.925451   28

## Analysis

In [54]:
print(max(temp_ech.index)-min(temp_ech.index))
temp_ech['2014-01-01']

880 days 00:00:00

               insee  tH2_obs        tH2  ech
date
2014-01-01   6088001      5.5   9.034338    1
2014-01-01   6088001      5.4   8.153351    2
2014-01-01   6088001      5.1   8.402343    3
2014-01-01   6088001      4.7   8.245682    4
2014-01-01   6088001      4.7   8.514988    5
2014-01-01   6088001      4.7   9.015853    6
2014-01-01   6088001      4.8   9.179396    7
2014-01-01   6088001      5.3   9.562431    8
2014-01-01   6088001      6.2  10.131776    9
2014-01-01   6088001      7.4  10.439922   10
2014-01-01   6088001     10.0  11.069077   11
2014-01-01   6088001     10.0  11.699109   12
2014-01-01   6088001     10.3  12.153840   13
2014-01-01   6088001     10.6  12.464955   14
2014-01-01   6088001      9.8  12.101505   15
2014-01-01   6088001      8.4  12.021394   16
2014-01-01   6088001      8.6  11.785885   17
2014-01-01   6088001      7.8  11.401471   18
2014-01-01   6088001      7.7  11.205267   19
2014-01-01   6088001      7.9  11.167496   20
2014-01-01   6088001      8.1  11.227059   21
2014-01-01   6088001      7.8  11.187069   22
2014-01-01   6088001      8.0  11.142321   23
2014-01-01   6088001      8.2  11.024646   24
2014-01-01   6088001      7.9  10.973166   25
2014-01-01   6088001      7.9  10.941004   26
2014-01-01   6088001      8.2  11.033950   27
2014-01-01   6088001      8.0  10.925451   28
2014-01-01   6088001      7.8  11.262741   29
2014-01-01   6088001      7.8  11.657800   30
...              ...      ...        ...  ...
2014-01-01  75114001      7.0   7.208069    1
2014-01-01  75114001      6.9   7.282375    2
2014-01-01  75114001      7.2   7.424495    3
2014-01-01  75114001      7.0   6.700273    4
2014-01-01  75114001      7.0   6.784263    5
2014-01-01  75114001      7.0   7.359250    6
2014-01-01  75114001      7.1   7.147274    7
2014-01-01  75114001      7.3   6.889038    8
2014-01-01  75114001      7.7   6.962505    9
2014-01-01  75114001      8.1   7.575566   10
2014-01-01  75114001      8.7   8.255433   11
2014-01-01  75114001      9.1   8.632080   12
2014-01-01  75114001      9.3   9.289964   13
2014-01-01  75114001      9.8   9.621031   14
2014-01-01  75114001     10.4   9.844250   15
2014-01-01  75114001     10.7  10.010461   16
2014-01-01  75114001     10.4   9.981056   17
2014-01-01  75114001      9.7   9.821576   18
2014-01-01  75114001      9.5   9.400470   19
2014-01-01  75114001      9.5   9.273802   20
2014-01-01  75114001     10.3   9.455015   21
2014-01-01  75114001     10.3   9.702389   22
2014-01-01  75114001     10.4  10.003702   23
2014-01-01  75114001     10.8   9.940145   24
2014-01-01  75114001     10.8  10.317167   25
2014-01-01  75114001     10.9   9.685958   26
2014-01-01  75114001      9.5  10.071367   27
2014-01-01  75114001      9.6  10.283924   28
2014-01-01  75114001     10.4   9.272826   29
2014-01-01  75114001     10.3   9.153009   30

[210 rows x 4 columns]

On peut voir que quand temp à n+1 with ech=1 == temp à n with ech=25 but not true with other cols

In [38]:
from os import listdir

cols = ['date', 'insee', 'tH2_obs', 'tH2', 'ech']
df = pd.DataFrame(columns=cols+['tH2_ech_n'])
for file_number in range(1,36+1):
    tmp = pd.read_csv(data_path + 'train_' + str(file_number) + '.csv', header=0, 
                               delimiter=";",decimal=',',parse_dates=['date'], index_col='date', usecols=cols)
    if df.ech > 1:
        
    tmp['tH2_ech_n'] = pd.Series(np.empty((3,1)).fill(np.nan), index= tmp.index)
    
#     if df.ech
#     df = pd.concat([df, ])
# train.to_csv(data_path + "train.csv", sep=';', index=False)

# df.sort_values(['insee', 'ech'], ascending=[True, True], inplace=True)

In [51]:
a = tmp.index[8] - tmp.index[2]
a.days

1

In [84]:
(temp_ech.index[0]).day

1